@include('frontend.layouts.partial.frontendHeader')
@include('frontend.layouts.partial.hero')
@yield('index')
@include('frontend.layouts.partial.service')
@include('frontend.layouts.partial.frontendFooter')